Repository Scheduo/server, pull requests merged in 2025-08, with the labels that each got.

#93 :hammer: CustomAuthenticationEntryPoint 응답 포맷 수정
  src/main/java/com/example/scheduo/global/config/security/entry/CustomAuthenticationEntryPoint.java
  src/test/kotlin/com/example/scheduo/global/config/JwtAuthenticationTest.kt
Labels: :bug: Fix

#88 [Feat] 특정 캘린더 + 특정 날짜 일정 조회 api 구현
  src/main/java/com/example/scheduo/domain/schedule/controller/ScheduleController.java
  src/main/java/com/example/scheduo/domain/schedule/dto/ScheduleResponseDto.java
  src/main/java/com/example/scheduo/domain/schedule/repository/ScheduleJpqlRepository.java
  src/main/java/com/example/scheduo/domain/schedule/repository/impl/ScheduleJpqlRepositoryImpl.java
  src/main/java/com/example/scheduo/domain/schedule/service/Impl/ScheduleServiceImpl.java
  src/main/java/com/example/scheduo/domain/schedule/service/ScheduleService.java
  src/test/kotlin/com/example/scheduo/domain/schedule/controller/ScheduleControllerTest.kt
Labels: :sparkles: Feat, :white_check_mark: Test

#100 일정 수정 API 구현
  src/main/java/com/example/scheduo/domain/calendar/entity/Calendar.java
  src/main/java/com/example/scheduo/domain/schedule/controller/ScheduleController.java
  src/main/java/com/example/scheduo/domain/schedule/dto/ScheduleRequestDto.java
  src/main/java/com/example/scheduo/domain/schedule/entity/Exception.java
  src/main/java/com/example/scheduo/domain/schedule/entity/Recurrence.java
  src/main/java/com/example/scheduo/domain/schedule/entity/Schedule.java
  src/main/java/com/example/scheduo/domain/schedule/service/Impl/ScheduleServiceImpl.java
  src/main/java/com/example/scheduo/domain/schedule/service/ScheduleService.java
  src/main/resources/application.yml
  src/test/kotlin/com/example/scheduo/domain/schedule/controller/UpdateScheduleTest.kt
Labels: :sparkles: Feat

#102 :hammer: 일정 상세 조회 수정
  src/main/java/com/example/scheduo/domain/schedule/controller/ScheduleController.java
  src/main/java/com/example/scheduo/domain/schedule/dto/ScheduleResponseDto.java
  src/main/java/com/example/scheduo/domain/schedule/entity/Schedule.java
  src/main/java/com/example/scheduo/domain/schedule/service/Impl/ScheduleServiceImpl.java
  src/main/java/com/example/scheduo/domain/schedule/service/ScheduleService.java
  src/test/kotlin/com/example/scheduo/domain/schedule/controller/ScheduleControllerTest.kt
Labels: :bug: Fix

#106 [Fix] 특정 날짜 일정 조회 수정
  src/main/java/com/example/scheduo/domain/schedule/controller/ScheduleController.java
  src/main/java/com/example/scheduo/domain/schedule/dto/ScheduleResponseDto.java
  src/main/java/com/example/scheduo/domain/schedule/service/Impl/ScheduleServiceImpl.java
  src/test/kotlin/com/example/scheduo/domain/schedule/controller/ScheduleControllerTest.kt
Labels: :bug: Fix

#112 [Feat] 일정 삭제 API 구현
  src/main/java/com/example/scheduo/domain/calendar/entity/Calendar.java
  src/main/java/com/example/scheduo/domain/schedule/controller/ScheduleController.java
  src/main/java/com/example/scheduo/domain/schedule/entity/Schedule.java
  src/main/java/com/example/scheduo/domain/schedule/service/Impl/ScheduleServiceImpl.java
  src/main/java/com/example/scheduo/domain/schedule/service/ScheduleService.java
  src/test/kotlin/com/example/scheduo/domain/schedule/controller/DeleteScheduleTest.kt
Labels: :sparkles: Feat
