Repository Scheduo/server, pull requests merged in 2025-06, with the labels that each got.

#10 [Feat] 캘린더 생성 Api 구현
  build.gradle
  src/main/java/com/example/scheduo/domain/calendar/controller/CalendarController.java
  src/main/java/com/example/scheduo/domain/calendar/dto/CalendarRequestDto.java
  src/main/java/com/example/scheduo/domain/calendar/dto/CalendarResponseDto.java
  src/main/java/com/example/scheduo/domain/calendar/entity/Calendar.java
  src/main/java/com/example/scheduo/domain/calendar/repository/CalendarRepository.java
  src/main/java/com/example/scheduo/domain/calendar/service/CalendarService.java
  src/main/java/com/example/scheduo/domain/calendar/service/impl/CalendarServiceImpl.java
  src/main/java/com/example/scheduo/global/response/ApiResponse.java
  src/main/java/com/example/scheduo/global/response/exception/GlobalExceptionHandler.java
  src/main/java/com/example/scheduo/global/response/status/ResponseStatus.java
Labels: :sparkles: Feat

#34 [Fix] 캘린더 초대 시 알림 생성
  build.gradle
  src/main/java/com/example/scheduo/domain/calendar/controller/CalendarController.java
  src/main/java/com/example/scheduo/domain/calendar/repository/CalendarJpqlRepository.java
  src/main/java/com/example/scheduo/domain/calendar/repository/CalendarRepository.java
  src/main/java/com/example/scheduo/domain/calendar/repository/impl/CalendarJpqlRepositoryImpl.java
  src/main/java/com/example/scheduo/domain/calendar/service/impl/CalendarServiceImpl.java
  src/main/java/com/example/scheduo/domain/member/dto/NotificationResponseDto.java
  src/main/java/com/example/scheduo/domain/member/entity/Notification.java
  src/main/java/com/example/scheduo/domain/member/entity/NotificationType.java
  src/main/java/com/example/scheduo/domain/member/service/NotificationService.java
  src/main/java/com/example/scheduo/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/scheduo/domain/member/service/impl/NotificationServiceImpl.java
  src/main/java/com/example/scheduo/global/config/AsyncConfig.java
  src/main/java/com/example/scheduo/global/config/SwaggerConfig.java
  src/main/java/com/example/scheduo/global/event/CalendarInvitationEvent.java
  src/main/java/com/example/scheduo/global/event/handler/CalendarInvitationEventHandler.java
  src/test/kotlin/com/example/scheduo/domain/calendar/controller/CalendarControllerTest.kt
  src/test/kotlin/com/example/scheduo/fixture/MemberFixture.kt
Labels: :bug: Fix

#45 [Feat] 캘린더 삭제 Api 구현
  src/main/java/com/example/scheduo/domain/calendar/controller/CalendarController.java
  src/main/java/com/example/scheduo/domain/calendar/service/CalendarService.java
  src/main/java/com/example/scheduo/domain/calendar/service/impl/CalendarServiceImpl.java
  src/test/kotlin/com/example/scheduo/domain/calendar/controller/CalendarControllerTest.kt
Labels: :sparkles: Feat, :white_check_mark: Test

#43 [Feat] 모든 캘린더 조회 Api 구현
  src/main/java/com/example/scheduo/domain/calendar/controller/CalendarController.java
  src/main/java/com/example/scheduo/domain/calendar/dto/CalendarResponseDto.java
  src/main/java/com/example/scheduo/domain/calendar/repository/ParticipantJpqlRepository.java
  src/main/java/com/example/scheduo/domain/calendar/repository/impl/ParticipantJpqlRepositoryImpl.java
  src/main/java/com/example/scheduo/domain/calendar/service/CalendarService.java
  src/main/java/com/example/scheduo/domain/calendar/service/impl/CalendarServiceImpl.java
  src/test/kotlin/com/example/scheduo/domain/calendar/controller/CalendarControllerTest.kt
Labels: :sparkles: Feat, :white_check_mark: Test

#47 [Refactor] 캘린더 초대, 수락, 거절 수정
  src/main/java/com/example/scheduo/domain/calendar/controller/CalendarController.java
  src/main/java/com/example/scheduo/domain/calendar/entity/Calendar.java
  src/main/java/com/example/scheduo/domain/calendar/entity/Participant.java
  src/main/java/com/example/scheduo/domain/calendar/service/CalendarService.java
  src/main/java/com/example/scheduo/domain/calendar/service/impl/CalendarServiceImpl.java
  src/main/java/com/example/scheduo/global/response/status/ResponseStatus.java
Labels: :recycle: Refactor

#55 [Fix] 캘린더 삭제 api 수정 및 캘린더 관련 api 인증 요청 방식 수정
  src/main/java/com/example/scheduo/domain/calendar/controller/CalendarController.java
  src/main/java/com/example/scheduo/domain/calendar/service/CalendarService.java
  src/main/java/com/example/scheduo/domain/calendar/service/impl/CalendarServiceImpl.java
  src/main/java/com/example/scheduo/domain/schedule/entity/Exception.java
  src/main/java/com/example/scheduo/domain/schedule/entity/Schedule.java
Labels: :bug: Fix

#66 [Fix] NotificationController 테스트 코드 수정
  src/test/kotlin/com/example/scheduo/domain/member/controller/NotificationControllerTest.kt
Labels: :bug: Fix, :white_check_mark: Test
